### ISSUE TITLE
flow_server_running is unnecessary and incompatible with external flow commands

### ISSUE THREAD

**Issue by jedwards1211** [diegodurli/flow-status-webpack-plugin#1]
I'm going to make a PR for this.

The way this variable is used, if the user started the flow server themselves, this plugin won't run `flow status`.

But, that's possible without breaking support for `options.interfacesPath`.  I will demonstrate how in my PR.

**Comment by jedwards1211** [comment]
I fixed this in https://github.com/diegodurli/flow-status-webpack-plugin/pull/2, though I replaced the `interfacesPath` option with a `flowArgs` option, to make it more generic.

**Comment by diegodurli** [comment]
Got it @jedwards1211, thanks for your PR! Will merge it!
