### ISSUE TITLE
Allow specification of flow binary location

### ISSUE THREAD

**Issue by garetht** [diegodurli/flow-status-webpack-plugin#5]
I was attempting to use this with the `webpack-dev-server`, but ran into this error, which I assume is caused by a complete lack of setup in `sh`, which I do not use: `/bin/sh: flow: command not found`. An option to specify where the flow binary can be found might help to solve the problem. This might also be helpful for people who do not have `flow` installed globally.

**Comment by diegodurli** [comment]
Hi @garetht! Thanks for your feedback on this.

I've pushed an update adding your request, allowing you to specify an external binary path.
Please, let me know if it suits your needs.

**Comment by diegodurli** [comment]
I'm closing it for now, but let me know if it did not worked well for you!

**Comment by garetht** [comment]
@diegodurli Thanks for implementing this!
